let country_code = {
    "AED": { code: "AE", name: "United Arab Emirates Dirham" },
    "AFN": { code: "AF", name: "Afghan Afghani" },
    "XCD": { code: "AG", name: "East Caribbean Dollar" },
    "ALL": { code: "AL", name: "Albanian Lek" },
    "AMD": { code: "AM", name: "Armenian Dram" },
    "ANG": { code: "AN", name: "Netherlands Antillean Guilder" },
    "AOA": { code: "AO", name: "Angolan Kwanza" },
    "AQD": { code: "AQ", name: "Antarctican Dollar" },
    "ARS": { code: "AR", name: "Argentine Peso" },
    "AUD": { code: "AU", name: "Australian Dollar" },
    "AZN": { code: "AZ", name: "Azerbaijani Manat" },
    "BAM": { code: "BA", name: "Bosnia-Herzegovina Convertible Mark" },
    "BBD": { code: "BB", name: "Barbadian Dollar" },
    "BDT": { code: "BD", name: "Bangladeshi Taka" },
    "XOF": { code: "BE", name: "West African CFA Franc" },
    "BGN": { code: "BG", name: "Bulgarian Lev" },
    "BHD": { code: "BH", name: "Bahraini Dinar" },
    "BIF": { code: "BI", name: "Burundian Franc" },
    "BMD": { code: "BM", name: "Bermudian Dollar" },
    "BND": { code: "BN", name: "Brunei Dollar" },
    "BOB": { code: "BO", name: "Bolivian Boliviano" },
    "BRL": { code: "BR", name: "Brazilian Real" },
    "BSD": { code: "BS", name: "Bahamian Dollar" },
    "NOK": { code: "BV", name: "Norwegian Krone" },
    "BWP": { code: "BW", name: "Botswana Pula" },
    "BYR": { code: "BY", name: "Belarusian Ruble" },
    "BZD": { code: "BZ", name: "Belize Dollar" },
    "CAD": { code: "CA", name: "Canadian Dollar" },
    "CDF": { code: "CD", name: "Congolese Franc" },
    "XAF": { code: "CF", name: "Central African CFA Franc" },
    "CHF": { code: "CH", name: "Swiss Franc" },
    "CLP": { code: "CL", name: "Chilean Peso" },
    "CNY": { code: "CN", name: "Chinese Yuan" },
    "COP": { code: "CO", name: "Colombian Peso" },
    "CRC": { code: "CR", name: "Costa Rican Colón" },
    "CUP": { code: "CU", name: "Cuban Peso" },
    "CVE": { code: "CV", name: "Cape Verdean Escudo" },
    "CYP": { code: "CY", name: "Cypriot Pound" },
    "CZK": { code: "CZ", name: "Czech Koruna" },
    "DJF": { code: "DJ", name: "Djiboutian Franc" },
    "DKK": { code: "DK", name: "Danish Krone" },
    "DOP": { code: "DO", name: "Dominican Peso" },
    "DZD": { code: "DZ", name: "Algerian Dinar" },
    "ECS": { code: "EC", name: "Ecuadorian Sucre" },
    "EEK": { code: "EE", name: "Estonian Kroon" },
    "EGP": { code: "EG", name: "Egyptian Pound" },
    "ETB": { code: "ET", name: "Ethiopian Birr" },
    "EUR": { code: "FR", name: "Euro" },
    "FJD": { code: "FJ", name: "Fijian Dollar" },
    "FKP": { code: "FK", name: "Falkland Islands Pound" },
    "GBP": { code: "GB", name: "British Pound Sterling" },
    "GEL": { code: "GE", name: "Georgian Lari" },
    "GGP": { code: "GG", name: "Guernsey Pound" },
    "GHS": { code: "GH", name: "Ghanaian Cedi" },
    "GIP": { code: "GI", name: "Gibraltar Pound" },
    "GMD": { code: "GM", name: "Gambian Dalasi" },
    "GNF": { code: "GN", name: "Guinean Franc" },
    "GTQ": { code: "GT", name: "Guatemalan Quetzal" },
    "GYD": { code: "GY", name: "Guyanese Dollar" },
    "HKD": { code: "HK", name: "Hong Kong Dollar" },
    "HNL": { code: "HN", name: "Honduran Lempira" },
    "HRK": { code: "HR", name: "Croatian Kuna" },
    "HTG": { code: "HT", name: "Haitian Gourde" },
    "HUF": { code: "HU", name: "Hungarian Forint" },
    "IDR": { code: "ID", name: "Indonesian Rupiah" },
    "ILS": { code: "IL", name: "Israeli New Shekel" },
    "INR": { code: "IN", name: "Indian Rupee" },
    "IQD": { code: "IQ", name: "Iraqi Dinar" },
    "IRR": { code: "IR", name: "Iranian Rial" },
    "ISK": { code: "IS", name: "Icelandic Króna" },
    "JMD": { code: "JM", name: "Jamaican Dollar" },
    "JOD": { code: "JO", name: "Jordanian Dinar" },
    "JPY": { code: "JP", name: "Japanese Yen" },
    "KES": { code: "KE", name: "Kenyan Shilling" },
    // Add more as needed
  };