const dropList = document.querySelectorAll(".drop-list select"),
fromCurrency = document.querySelector(".from select"),
toCurrency = document.querySelector(".to select"),
getButton = document.querySelector("form button");

for (let i = 0; i< dropList.length; i++) {
    for(currency_code in country_code){
        let selected;
        if(i == 0){
            selected = currency_code == "USD" ? "selected" : " ";
        } else if(i == 1){
            selected = currency_code == "INR" ? "selected" : " ";

        }
        let optionTag = `<option value="${currency_code}" ${selected}>${currency_code} - ${country_code[currency_code]}</option>`;
        dropList[i].insertAdjacentHTML("beforeend",optionTag)
    }
    dropList[i].addEventListener("change",e =>{
        loadFlag(e.target);
    });
}

function loadFlag(element){
    for(code in country_code){
        if(code == element.value){ // if currency code of country list is equal to option value
            let imgTag = element.parentElement.querySelector("img"); // selecting image tag of particular dopr list
            // passing country code of a selected currency code in image url
            imgTag.src = `https://flagsapi.com/${country_code[code]}/flat/64.png`
        }
    }
}
// this is generated by chat-gpt
// function loadFlag(element) {
//     const selectedCurrencyCode = element.value;
//     const flagImage = element.parentElement.querySelector('img');

//     // Assuming country_code object maps currency codes to country codes
//     const countryCode = country_code[selectedCurrencyCode];

//     if (country_code) {
//         flagImage.src = `https://flagsapi.com/${countryCode}/flat/64.png`;
//     } else {
//         // Handle cases where country code is not found
//         flagImage.src = 'default_flag.png'; // Replace with your default flag image
//     }
// }


window.addEventListener("load", ()=>{
    fromCurrency.value = "USD";
    toCurrency.value = "INR";
    getExchangerate();
});
getButton.addEventListener("click", e =>{
    e.preventDefault();
    getExchangerate();
});

const exchangeIcon = document.querySelector(".drop-list .icon");
exchangeIcon.addEventListener("click", ()=>{
    let tempCode = fromCurrency.value;
    fromCurrency.value = toCurrency.value;
    toCurrency.value = tempCode;
    loadFlag(fromCurrency);
    loadFlag(toCurrency);
    getExchangerate();
});

function getExchangerate(){
    const amount = document.querySelector(".amount input");
    const exchangeratetxt = document.querySelector(".exchange-rate");
    let amountVal = amount.value;
    if (amountVal == "" || amountVal == "0") {
        amount.value = "1";
        amountVal = 1;
    }
    exchangeratetxt.innerText = "Getting please wait...(from world's fastest server)";
    let url = `https://v6.exchangerate-api.com/v6/cd7004c4d2b05b8da46a71cf/latest/${fromCurrency.value}`;
    fetch(url)
        .then(response =>response.json()).then(result => {
            let exchangerate = result.conversion_rates[toCurrency.value];
            let totalExchangerate = (amountVal * exchangerate).toFixed(2);
            exchangeratetxt.innerText = `${amountVal} ${fromCurrency.value} = ${totalExchangerate} ${toCurrency.value}`
        }).catch(()=>{
            exchangeratetxt.innerText = "Something went wrong";
        });
    loadFlag(fromCurrency);
    loadFlag(toCurrency);
}